/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as TimeBlocksRouteImport } from './routes/time-blocks'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ActivityTypesRouteImport } from './routes/activity-types'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HabitsIndexRouteImport } from './routes/habits.index'
import { Route as HabitsHabitIdRouteImport } from './routes/habits.$habitId'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeBlocksRoute = TimeBlocksRouteImport.update({
  id: '/time-blocks',
  path: '/time-blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityTypesRoute = ActivityTypesRouteImport.update({
  id: '/activity-types',
  path: '/activity-types',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HabitsRoute,
} as any)
const HabitsHabitIdRoute = HabitsHabitIdRouteImport.update({
  id: '/$habitId',
  path: '/$habitId',
  getParentRoute: () => HabitsRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-types': typeof ActivityTypesRoute
  '/dashboard': typeof DashboardRoute
  '/habits': typeof HabitsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/time-blocks': typeof TimeBlocksRoute
  '/todos': typeof TodosRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/habits/': typeof HabitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-types': typeof ActivityTypesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/time-blocks': typeof TimeBlocksRoute
  '/todos': typeof TodosRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/habits': typeof HabitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-types': typeof ActivityTypesRoute
  '/dashboard': typeof DashboardRoute
  '/habits': typeof HabitsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/time-blocks': typeof TimeBlocksRoute
  '/todos': typeof TodosRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/habits/': typeof HabitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-types'
    | '/dashboard'
    | '/habits'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/stats'
    | '/time-blocks'
    | '/todos'
    | '/auth/verify'
    | '/habits/$habitId'
    | '/habits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-types'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/stats'
    | '/time-blocks'
    | '/todos'
    | '/auth/verify'
    | '/habits/$habitId'
    | '/habits'
  id:
    | '__root__'
    | '/'
    | '/activity-types'
    | '/dashboard'
    | '/habits'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/stats'
    | '/time-blocks'
    | '/todos'
    | '/auth/verify'
    | '/habits/$habitId'
    | '/habits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityTypesRoute: typeof ActivityTypesRoute
  DashboardRoute: typeof DashboardRoute
  HabitsRoute: typeof HabitsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  TimeBlocksRoute: typeof TimeBlocksRoute
  TodosRoute: typeof TodosRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-blocks': {
      id: '/time-blocks'
      path: '/time-blocks'
      fullPath: '/time-blocks'
      preLoaderRoute: typeof TimeBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-types': {
      id: '/activity-types'
      path: '/activity-types'
      fullPath: '/activity-types'
      preLoaderRoute: typeof ActivityTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/': {
      id: '/habits/'
      path: '/'
      fullPath: '/habits/'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof HabitsRoute
    }
    '/habits/$habitId': {
      id: '/habits/$habitId'
      path: '/$habitId'
      fullPath: '/habits/$habitId'
      preLoaderRoute: typeof HabitsHabitIdRouteImport
      parentRoute: typeof HabitsRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HabitsRouteChildren {
  HabitsHabitIdRoute: typeof HabitsHabitIdRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
}

const HabitsRouteChildren: HabitsRouteChildren = {
  HabitsHabitIdRoute: HabitsHabitIdRoute,
  HabitsIndexRoute: HabitsIndexRoute,
}

const HabitsRouteWithChildren =
  HabitsRoute._addFileChildren(HabitsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityTypesRoute: ActivityTypesRoute,
  DashboardRoute: DashboardRoute,
  HabitsRoute: HabitsRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  TimeBlocksRoute: TimeBlocksRoute,
  TodosRoute: TodosRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
